### ISSUE TITLE
Any plan to release the training code?

### ISSUE THREAD

**Issue by VimukthiRandika1997** [18907305772/FuseLLM#1]
I am really impressed with work, I would think how we can apply this to the other domains like computer vision.

Thank you!

**Comment by 18907305772** [comment]
FuseLLM only requires the extraction of the source model's representation of the training samples and then training the target model. Therefore, this approach can potentially be applied to other domains for knowledge fusion of multiple structurally diverse models as well.

We will release the code this week!

Thank you for your interest!

**Comment by VimukthiRandika1997** [comment]
@18907305772  Thank you very much!
