### ISSUE TITLE
minipile_split issue

### ISSUE THREAD

**Issue by Arbor334** [18907305772/FuseLLM#8]
When I change the path in split_long_text.py  to my own directory, i got 
![2024-03-09-09-50-06-image](https://github.com/18907305772/FuseLLM/assets/57646922/a77cf644-c0d0-4745-949a-97f6e8365080)

is it right？

**Comment by 18907305772** [comment]
Hello, @Arbor334. It's correct to tokenize the long sequence and split it into short chunks.

**Comment by Arbor334** [comment]
![image](https://github.com/18907305772/FuseLLM/assets/57646922/bf310cee-ec1e-483f-b99d-6766e4680c1f)
thanks @18907305772  ,If the above splitting of the data set is completed, I will implement the different scripts below, corresponding to `llama` , `open_llama` `mpt`, respectively.
![image](https://github.com/18907305772/FuseLLM/assets/57646922/dda9b773-f3ab-44b0-b074-80ef1da55acb)

**Comment by 18907305772** [comment]
That's right. It is recommended to test the code on a small subset before running it on the entire dataset.

**Comment by Arbor334** [comment]
Thank you @18907305772   , I will adopt your suggestion
